### ISSUE TITLE
contact Joey to see if we have building access 

### ISSUE THREAD

**Issue by equilet** [Berkeley-MDes/desinv-202#1]
via cards

**Comment by loopstick** [comment]
email sent. No response yet

**Comment by equilet** [comment]
answer is yes during business hours 9-5ish: we also need to have special access for class hours.  @loopstick is going through the flow with Amy/Joey

**Comment by loopstick** [comment]
Jacobs is open during business hours. We can access 310 but not the makerspace or MDes lounge.
Our faculty office is in 310A. There's a lockbox with a key in ti. the code is 2-4-6-8.

We will have full after hours and makerspace access when the semester starts.

Before then, we are waiting for Amy to approve after hours and makerspace access. 
Once approved Joey will code our keycard for after hours and makerspace access.
I just sent Kyle an email to ask about making this happen sooner than later.
