### ISSUE TITLE
questionnaire for incoming cohort

### ISSUE THREAD

**Issue by equilet** [Berkeley-MDes/desinv-202#11]
let's include a requirement for Jacobs training

**Comment by tj60647** [comment]
I have discussed the questionnaire with my in-house design research consultant. I will continue to follow up with them.

The questionnaire will be delivered to their USB email address via google survey and responses will be gathered and collated into a Google sheet for further analysis.  This should be executed 10 days before the first class.

I believe the goal of the questionnaire is to help establish a baseline for incoming students' experience, expectations, desires, and skill sets.

Off the top of my head, to be discussed with this team and design research:

- What is your background?
- Why are you in the MDes program?
- What do you hope to accomplish in this course?
- What excites you about emerging technologies?
- Where do you see yourself in 5 years?

- Do you have experience with X?  CAD, Fabrication, Software, Hardware, AI, collaboration tools, etc. [the stuff we plan to use to elevate skillsets]
- Can you Y with X? [as opposed to a scale of 1-10 or something referenceless]

- Do you have experience working in teams?  What has worked well in your best experience? What has not worked well? What kinds of collaboration tools and methods did you use?

**Comment by tj60647** [comment]
Let us add questions about video content production.

Have you ever made a 2-3 minute video? [for instance tiktok/instagram]
What tools did you use? What tools would you recommend to a classmate who has not done this before?

**Comment by tj60647** [comment]
The survey will be prepared using Google Forms:  https://www.google.com/forms/about/
The responses will be collected and analyzed in [an auto-generated] google sheet.

**Comment by equilet** [comment]
Here is my former list made as we were discussing this initially:

- What is your background? (duplicate)
- What is it about Designing things that interests you?
- What do you anticipate getting out of this course? (duplicate)
- What do you see yourself doing in 5 years?  10 years? (semi-duplicate)
- Tell us a bit about your technical experience as it may pertain to design
- Do you have experience working on a team in a professional context?  If so, please tell us more about that (semi-duplicate)

**Comment by tj60647** [comment]
https://docs.google.com/forms/d/1_KOaPJRDtA4wVkW_3LD0Qimdbb1Bv9DIL0Dw0CsBnx8/edit

https://docs.google.com/spreadsheets/d/136OrQytHJcXkYI5hM95xF5y7FxFbow_et0QSa5LDxA4/edit?usp=sharing
