### ISSUE TITLE
document installation procedure for VSCode

### ISSUE THREAD

**Issue by loopstick** [Berkeley-MDes/desinv-202#17]
and whatever other VSCode plugins/extensions we anticipate using: Particle Workbench, etc

once documented, Sudhu will test the procedure
(Jeff reassign to Sudhu once documentation is complete)

**Comment by equilet** [comment]
just answering your question above:  yes
...more to come.

**Comment by equilet** [comment]
[Here is the page](https://github.com/Berkeley-MDes/desinv-202/wiki/Installing-Visual-Studio-Code-&-TDF-Extensions).
Let me know how it goes!

**Comment by equilet** [comment]
updated link

**Comment by LoopstickCal** [comment]
step 2:

	2.	replace "install via the installer prompts" with "unzip" 
	3.	drag the application to your Applications folder

**Comment by equilet** [comment]
I do not know if you need to do this on windows; it's typical that you don't as there can be a Setup.exe

**Comment by equilet** [comment]
I did make the other change - thanks!
I'm going to close this issue for now, but feel free to reopen it if you think we missed something.
