### ISSUE TITLE
Test Photon Wifi access

### ISSUE THREAD

**Issue by loopstick** [Berkeley-MDes/desinv-202#2]
...and update docs

**Comment by equilet** [comment]
IoT network:  how does one authenticate?

**Comment by equilet** [comment]
closing in favor of https://github.com/Berkeley-MDes/desinv-202/issues/3

**Comment by loopstick** [comment]
I think the point of the IoT network is that you don't have to authenticate. 
All you need is the generated password associated with your device's MAC address

yes, it appears the network is accessible throughout campus.
