### ISSUE TITLE
Identify technique for supporting 'participation'

### ISSUE THREAD

**Issue by tj60647** [Berkeley-MDes/desinv-202#21]
We have an evaluation and grading procedure tied to attendance and participation in the syllabus.  We need to identify a technique for doing so that is low effort, scalable, and effective.  I have a proposal [needs modification] that uses google survey and google sheets to track these things as well as encourage team collaboration whether project-based or as a workgroup.

**Comment by equilet** [comment]
from today's meeting:  TJ will migrate a naked version of this doc template to our TDF gdrive space

**Comment by tj60647** [comment]
build a basic survey based on past work tailored for the student workgroup setups.
