### ISSUE TITLE
slide deck for 1st day

### ISSUE THREAD

**Issue by equilet** [Berkeley-MDes/desinv-202#25]
collaborative

**Comment by loopstick** [comment]
can use this _incomplete_ [class 1 lesson plan](https://docs.google.com/document/d/1lISMyKIog6ifm1Oesd5UsLjwob_2uiblClKVw3v2gYs/edit?usp=sharing) as an outline for slides

**Comment by loopstick** [comment]
https://docs.google.com/presentation/d/1iBRnSy-_mTjsAq3iS0EJUN6XGyUCDqJ3iCjx2jGg8co/edit?usp=sharing
