### ISSUE TITLE
media sources to show in class lectures / discussions

### ISSUE THREAD

**Issue by equilet** [Berkeley-MDes/desinv-202#8]
I prefer to avoid YouTube if possible as it's nothing but ads (unless there is a good solution).
- LinkedIn learning
- coursera
- wikipedia
- vimeo

Please suggest others

**Comment by loopstick** [comment]
we can install adBlocker (assuming we're ruing our laptops to show YouTube media)

**Comment by equilet** [comment]
which one do you like?  I have a few and none of them work

**Comment by loopstick** [comment]
AdBlock: https://getadblock.com/en/
AdBlock<https://getadblock.com/en/>
AdBlock is a user-supported browser extension that lets you surf the web ad-free.
getadblock.com

________________________________

**Comment by equilet** [comment]
I will go through and organize by activity- wiki?

**Comment by loopstick** [comment]
https://github.com/Berkeley-MDes/desinv-202/wiki/Resources-&-Useful-Links-for-Students
